apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksmanagement
  labels:
    app: booksmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksmanagement
  template:
    metadata:
      labels:
        app: booksmanagement
    spec:
      containers:
        - name: booksmanagement
          image: "username/booksmanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
