apiVersion: apps/v1
kind: Deployment
metadata:
  name: authidentity
  labels:
    app: authidentity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authidentity
  template:
    metadata:
      labels:
        app: authidentity
    spec:
      containers:
        - name: authidentity
          image: "username/authidentity:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
