---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admintask
  labels:
    app: admintask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admintask
  template:
    metadata:
      labels:
        app: admintask
    spec:
      containers:
        - name: admintask
          image: username/admintask:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monthlysubscriptionmanagement
  labels:
    app: monthlysubscriptionmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monthlysubscriptionmanagement
  template:
    metadata:
      labels:
        app: monthlysubscriptionmanagement
    spec:
      containers:
        - name: monthlysubscriptionmanagement
          image: username/monthlysubscriptionmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfomanagement
  labels:
    app: userinfomanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinfomanagement
  template:
    metadata:
      labels:
        app: userinfomanagement
    spec:
      containers:
        - name: userinfomanagement
          image: username/userinfomanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authidentity
  labels:
    app: authidentity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authidentity
  template:
    metadata:
      labels:
        app: authidentity
    spec:
      containers:
        - name: authidentity
          image: username/authidentity:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointmanagement
  labels:
    app: pointmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointmanagement
  template:
    metadata:
      labels:
        app: pointmanagement
    spec:
      containers:
        - name: pointmanagement
          image: username/pointmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scriptmanagement
  labels:
    app: scriptmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scriptmanagement
  template:
    metadata:
      labels:
        app: scriptmanagement
    spec:
      containers:
        - name: scriptmanagement
          image: username/scriptmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userhistorymanagement
  labels:
    app: userhistorymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userhistorymanagement
  template:
    metadata:
      labels:
        app: userhistorymanagement
    spec:
      containers:
        - name: userhistorymanagement
          image: username/userhistorymanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiservice
  labels:
    app: aiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiservice
  template:
    metadata:
      labels:
        app: aiservice
    spec:
      containers:
        - name: aiservice
          image: username/aiservice:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksmanagement
  labels:
    app: booksmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksmanagement
  template:
    metadata:
      labels:
        app: booksmanagement
    spec:
      containers:
        - name: booksmanagement
          image: username/booksmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksubstriptionmanagement
  labels:
    app: booksubstriptionmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksubstriptionmanagement
  template:
    metadata:
      labels:
        app: booksubstriptionmanagement
    spec:
      containers:
        - name: booksubstriptionmanagement
          image: username/booksubstriptionmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: admintask
  labels:
    app: admintask
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: admintask


---


apiVersion: v1
kind: Service
metadata:
  name: monthlysubscriptionmanagement
  labels:
    app: monthlysubscriptionmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: monthlysubscriptionmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: userinfomanagement
  labels:
    app: userinfomanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userinfomanagement


---


apiVersion: v1
kind: Service
metadata:
  name: authidentity
  labels:
    app: authidentity
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authidentity


---


apiVersion: v1
kind: Service
metadata:
  name: pointmanagement
  labels:
    app: pointmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pointmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: scriptmanagement
  labels:
    app: scriptmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: scriptmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: userhistorymanagement
  labels:
    app: userhistorymanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userhistorymanagement


---


apiVersion: v1
kind: Service
metadata:
  name: aiservice
  labels:
    app: aiservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aiservice


---


apiVersion: v1
kind: Service
metadata:
  name: booksmanagement
  labels:
    app: booksmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: booksmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: booksubstriptionmanagement
  labels:
    app: booksubstriptionmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: booksubstriptionmanagement

