apiVersion: apps/v1
kind: Deployment
metadata:
  name: admintask
  labels:
    app: admintask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admintask
  template:
    metadata:
      labels:
        app: admintask
    spec:
      containers:
        - name: admintask
          image: "username/admintask:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
