server:
  port: 8080

# JWT 설정
jwt:
  secret: aivleSecretKeyForJWTTokenGeneration2024WithMoreThan256BitsToMeetSecurityRequirements
  expiration: 86400

spring:
  application:
    name: authidentity
---

spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: authidentity
#<<< EDA / Topic Name
          destination: aivle
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: aivle
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
#     org.hibernate.type: trace
#     org.springframework.cloud: debug
    root: ERROR
    aivle: INFO
    org.springframework.cloud: ERROR
    org.hibernate: ERROR
    org.springframework.boot: ERROR
    org.springframework.web: ERROR

api:
  url: 
    authidentity: localhost:8085 
    

server:
  port: 8085

---

spring:
  profiles: docker

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: authidentity
          destination: aivle
          contentType: application/json
        event-out:
          destination: aivle
          contentType: application/json

server:
  port: 8080

api:
  url: 
    authidentity: authidentity:8080 
    

