apiVersion: v1
kind: Service
metadata:
  name: userhistorymanagement
  labels:
    app: userhistorymanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userhistorymanagement