apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksubstriptionmanagement
  labels:
    app: booksubstriptionmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booksubstriptionmanagement
  template:
    metadata:
      labels:
        app: booksubstriptionmanagement
    spec:
      containers:
        - name: booksubstriptionmanagement
          image: "username/booksubstriptionmanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
