apiVersion: v1
kind: Service
metadata:
  name: booksubstriptionmanagement
  labels:
    app: booksubstriptionmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: booksubstriptionmanagement