apiVersion: v1
kind: Service
metadata:
  name: monthlysubscriptionmanagement
  labels:
    app: monthlysubscriptionmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: monthlysubscriptionmanagement